ALTER TABLE account_limits
ADD COLUMN block_online BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN block_contactless BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN contactless_limit DECIMAL(19, 4),
ADD COLUMN block_atm BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN block_gambling BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN block_entertainment BOOLEAN NOT NULL DEFAULT FALSE;
