ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN mfa_secret VARCHAR(100);
ALTER TABLE users ADD COLUMN kyc_status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE users ADD COLUMN kyc_document_type VARCHAR(20);
ALTER TABLE users ADD COLUMN kyc_document_base64 TEXT;
